version: '{build}'

environment:
  TX_TOKEN:
    secure: JnaLs853x8HUamXsyYBwnbAx5Ap9ETi+c8Lzx1SBeB8SJg+BSV86dZfSNEsspcdD
    
skip_tags: true

only_commits:
  files:
    - '**/*.json'

install:
  - pip install transifex-client
  - ps: ./tx.ps1 -Action Push

build: off
test: off
deploy: off